#!/usr/bin/env python
"""A script for managing autoscaling groups

Usage:
  scaling launch <ami>
  scaling terminate <ami>
  scaling terminate-others <ami>

Commands:
  launch    - Creates a launch configuration and autoscaling group for the AMI and attaches it to the ELB
  terminate - Terminates the launch configuration and autoscaling group created for the AMI (assuming they were created
              using our standard naming.

Options:
  -h --help     Show this screen.
  --version     Show version.
"""


from docopt import docopt
from amideploying.managers import shutdown_ag_by_ami, shutdown_other_ags, start_ag
from amideploying import __version__

if __name__ == '__main__':
    args = docopt(__doc__, version='Scaling {0}'.format(__version__))
    if args['launch']:
        start_ag(args.get("<ami>"))
    if args['terminate']:
        shutdown_ag_by_ami(args.get("<ami>"))
    if args['terminate-others']:
        shutdown_other_ags(args.get("<ami>"))